[pytest]
# Establece el directorio raíz del proyecto para la resolución de módulos
pythonpath = app

# Opción para mostrar todas las advertencias
addopts = --strict-markers --disable-warnings

# Muestra solo fallos detallados en los reportes
log_cli = true
log_cli_level = INFO

# Configuración para la detección de archivos de prueba
testpaths =
    app/tests

# Ignorar archivos específicos si es necesario
norecursedirs = .* build dist CVS
